---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    testc: host505
  name: guge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guge
  template:
    metadata:
      labels:
        app: guge
    spec:
      containers:
      - image: jim3ma/google-mirror
        name: guge
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    dev.okteto.com/auto-ingress: 'true'
  labels:
    testc: host6379
  name: guge
spec:
  ports:
  - name: http-port-tcp
    port: 80
  selector:
    app: guge
  type: ClusterIP
