name: okteto
on:
  schedule:
    - cron: 10 6,18 * * *
  watch:
    types: started      
jobs:
  build:
    runs-on: ubuntu-latest  
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.7]
        #python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install build dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install wget
        sudo apt-get -y install curl
    - name: Clone source
      run: |
        cd /home/runner
        wget https://github.com/okteto/okteto/releases/download/1.8.13/okteto-Linux-x86_64
        chmod +x ./okteto-Linux-x86_64
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
    - name: 开始推送
      run: |
        echo 'Hello World'
        pwd

        #更改yml随机数以方便‘开发’
        python modefied.py

        #okteto的api密钥
        /home/runner/okteto-Linux-x86_64 login --token ${{ secrets.APITOKEN }}

        #Namespace用户名
        /home/runner/okteto-Linux-x86_64 namespace ${{ secrets.namespace }}
        
        #google-mirror.yml     自己要部署项目
        kubectl --force -f /home/runner/work/okteto/okteto/google-mirror.yml    
        
